name: mcp_playground_flutter_example_embedded
description: "A secondary example showcasing mcp_playground with an initial on-device embedded LLM configuration."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  mcp_playground_flutter:
    path: ../mcp_playground_flutter
  mcp_playground_dart:
    path: ../mcp_playground_dart
  mcp_playground_shared_tools:
    path: ../example/shared_tools
  http: ^1.2.1
  dartssh2: ^2.18.0
  mime: ^2.0.0
  fl_chart: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
