include: package:lints/recommended.yaml

analyzer:
  errors:
    avoid_print: ignore
    avoid_relative_lib_imports: ignore

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_single_quotes
