// Generated by scripts/build_js_bridge.mjs from js/src/llama_webgpu_bridge_worker.js.
// Do not edit this file directly; update js/src/ and run npm run build:js.
import { enableBridgeWorkerHost } from './llama_webgpu_bridge.js';

enableBridgeWorkerHost();
